### ISSUE TITLE
Question: Shall adding foreign key constraint in `access_tokens` table for `user_id` column be an additional overhead

### ISSUE THREAD

**Issue by SamarRizvi** [kot13/bootstrapi#14]
If **foreign key constraint** for `user_id `is added in `access_tokens` table, shall it be an additional overhead when there are large number of users. I am asking this because, when I add foreign key constraint to user_id field, the index on it is removed, and indexing is for sure, good when there are large number of users. Or is it that adding a foreign key constraint to a column is automatically indexed.

So what to use, **foreign key constraint** or **index** for `user_id`?

**Comment by kot13** [comment]
Is there a search in `access_token` table by `user_id`? 
It seems no. Therefore, I think that the index is not needed.

But foreign key constraint for `user_id` also increases overhead. Maybe it is not necessary?

For maximum performance, you should use key-value storage (Redis for example).
