### ISSUE TITLE
конфиги

### ISSUE THREAD

**Issue by wormen** [kot13/bootstrapi#3]
Рассматривался ли вариант, что не всегда есть возможность править конфигb nginx?
вероятно стоит добавить в ваш проект вариант с .htaccess

**Comment by wormen** [comment]
и сразу ответ .... у себя в связке nginx+apache, я использовал .htaccess такого содержания

```
DirectoryIndex index.php

<IfModule mod_env.c>
    SetEnv APPLICATION_ENV develop
    SetEnv SECRET_KEY mysecretkey
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On

    #API
    RewriteRule ^api/(.*)$ /index.php?q=$1 [L]

</IfModule>
```

1) этого оказалось более чем достаточно
2) этот файл можно добавить в состав репозитория

**Comment by kot13** [comment]
Думаю, нужно добавить пример конфига в readme. Только у меня нет apache, чтобы проверить работу. Вот я тут написал:
```
<VirtualHost *:80>
   ServerName hostname
   DocumentRoot "/path/to/projects/hostname/"

   <Directory "/path/to/projects/hostname/public">
       # use mod_env for define environment variables
       SetEnv APPLICATION_ENV develop
       SetEnv SECRET_KEY mysecretkey
   
       # use mod_rewrite for pretty URL support
       RewriteEngine on
       # If a directory or a file exists, use the request directly
       RewriteCond %{REQUEST_FILENAME} !-f
       RewriteCond %{REQUEST_FILENAME} !-d
       # Otherwise forward the request to index.php
       RewriteRule ^api/(.*)$ /index.php?q=$1 [L]

       # use index.php as index file
       DirectoryIndex index.php

       # ...other settings...
       # Apache 2.4
       Require all granted

       ## Apache 2.2
       # Order allow,deny
       # Allow from all
   </Directory>
</VirtualHost>

<VirtualHost *:80>
   ServerName docs.hostname
   DocumentRoot "/path/to/projects/hostname/docs"

   <Directory "/path/to/projects/hostname/docs">
       # use index.html as index file
       DirectoryIndex index.html

       # ...other settings...
       # Apache 2.4
       Require all granted

       ## Apache 2.2
       # Order allow,deny
       # Allow from all
   </Directory>
</VirtualHost>
```

Помоги, пожалуйста, привести его в рабочий вид.

**Comment by wormen** [comment]
@kot13 Вероятно Вы не поняли, о чем я
**нужно привести настройки к тому состоянию, чтобы НЕ править конфиги сервера**

простой пример
есть самый обычный хостинг, где вам запрещено менять конфиги сервера

что будите делать в этом случае?

тот пример выше, который я описал для .htaccess, это рабочий конфиг, с помощью которого я завел ваш проект, без правки конфигов nginx или apache

**Comment by wormen** [comment]
еще совет ... 
ориентируйтесь на пользователей, которые будут разворачивать ваш продукт на самом плохом хостинге, и с максимальными ограничениями

насколько для Вас полезен этот совет, решайте сами
